"use client";

import { useUser } from '@auth0/nextjs-auth0/client'
import PageLayout from "../components/page-layout";
import type { Metadata } from 'next'
import { experimental_useFormStatus } from 'react-dom';
import React from 'react';
export const metadata: Metadata = {
    title: 'About Monnies',
    description: 'Generated by create next app',
  }
    
// components/BudgetView.js


const budgetData = {
  expenses: {
    fixed: {
      rent: 1400,
      utilities: 200,
      internet: 50,
      insurance: 150,
      loan_repayment: 300,
      subscriptions: 50,
    },
    variable: {
      groceries: 400,
      dining_out: 200,
      transportation: 150,
      entertainment: 100,
      clothing: 100,
      personal_care: 50,
    },
  },
  debt_payments: {
    credit_card: 200,
    personal_loans: 150,
  },
  irregular: {
    annual_subscriptions: 120,
    property_taxes: 250,
    vehicle_maintenance: 100,
  },
  miscellaneous: 100,
};

const Budget = () => {
    const { user, isLoading } = useUser(); 
    const { expenses, debt_payments, irregular, miscellaneous } = budgetData;

    return (
    <PageLayout user={user} loading={isLoading}>
    <div>
      <h1>Budget View</h1>
      <h2>Expenses</h2>
      <table className='table-auto'>
        <thead>
          <tr>
            <th>Category</th>
            <th>Item</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(expenses).map(([category, items]) => (
            <React.Fragment key={category}>
              <tr>
                <td colSpan="3" style={{ fontWeight: 'bold' }}>
                  {category} expenses
                </td>
              </tr>
              {Object.entries(items).map(([item, amount]) => (
                <tr key={item}>
                  <td></td>
                  <td>{item}</td>
                  <td>${amount}</td>
                </tr>
              ))}
            </React.Fragment>
          ))}
        </tbody>
      </table>

      <h2>Debt Payments</h2>
      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(debt_payments).map(([item, amount]) => (
            <tr key={item}>
              <td>{item}</td>
              <td>${amount}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Irregular Expenses</h2>
      <table>
        <thead>
          <tr>
            <th>Item</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(irregular).map(([item, amount]) => (
            <tr key={item}>
              <td>{item}</td>
              <td>${amount}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Miscellaneous</h2>
      <p>Miscellaneous Expenses: ${miscellaneous}</p>
    </div>
        </PageLayout>
    )
}

export default Budget;